import enum
import math

WIDTH = 1400  # フィールドの幅 (1pixel当たり1cmとする)
HEIGHT = 900  # フィールドの高さ
PENALTY_WIDTH = 300  # ペナルティエリアの幅
PENALTY_HEIGHT = 600  # ペナルティエリアの高さ
GOALAREA_WIDTH = 100  # ゴールエリアの幅
GOALAREA_HEIGHT = 400  # ゴールエリアの高さ

# フィールドの設定
FIELD_COLOR = (0, 150, 0)
LINE_COLOR = (255, 255, 255)
GOAL_COLOR = (255, 0, 0)  # ゴールの色
BALL_COLOR = (255, 255, 0)

ROBOT_COLOR = (0, 0, 255)
ROBOT_SIZE = 40  # ロボットのサイズ

ROBOT_MAX_SPEED_X_PLUS = 4.0 / 4.138  # 4.138秒で4m進むのが最大速度
ROBOT_MAX_SPEED_X_MINUS = -4.0 / 4.322  # 4.322秒で4m下がるのが最大速度
ROBOT_MAX_SPEED_Y = 4.0 / 10.55  # 10.55秒で4m進むのが最大速度
ROBOT_MAX_SPEED_PI = 2 * math.pi / 4.492  # 4.492秒で360度回転が最大速度

SIM_FPS = 60  # シミュレーションの更新頻度（FPS）

# シミュレーション上での距離計算を実機と同じになるように補正するスケール
DETECTION_DISTANCE_SCALE_X = 1.2
DETECTION_DISTANCE_SCALE_Y = 1.0

# 各オブジェクトの絶対座標 (左上が0,0)

GOALPOST_LEFT_UP = (0, HEIGHT / 2 - 260 / 2)
GOALPOST_LEFT_DOWN = (0, HEIGHT / 2 + 260 / 2)
GOALPOST_RIGHT_UP = (WIDTH, HEIGHT / 2 - 260 / 2)
GOALPOST_RIGHT_DOWN = (WIDTH, HEIGHT / 2 + 260 / 2)
PENALTY_MARK_LEFT = (210, HEIGHT / 2)
PENALTY_MARK_RIGHT = (WIDTH - 210, HEIGHT / 2)
KICKOFF_MARK = (WIDTH // 2, HEIGHT // 2)
CENTORLINE_CIRCLE_INTERSEC_UP = (WIDTH // 2, HEIGHT // 2 - 150)
CENTORLINE_CIRCLE_INTERSEC_DOWN = (WIDTH // 2, HEIGHT // 2 + 150)
CENTORLINE_SIDELINE_INTERSEC_UP = (WIDTH // 2, 0)
CENTORLINE_SIDELINE_INTERSEC_DOWN = (WIDTH // 2, HEIGHT)
RIGHT_CORNER_UP = (WIDTH, 0)
RIGHT_CORNER_DOWN = (WIDTH, HEIGHT)
LEFT_CORNER_UP = (0, 0)
LEFT_CORNER_DOWN = (0, HEIGHT)
RIGHT_PENALTYAREA_CORNER_RIGHT_UP = (WIDTH, (HEIGHT - PENALTY_HEIGHT) // 2)
RIGHT_PENALTYAREA_CORNER_RIGHT_DOWN = (
    WIDTH,
    (HEIGHT - PENALTY_HEIGHT) // 2 + PENALTY_HEIGHT,
)
RIGHT_PENALTYAREA_CORNER_LEFT_UP = (
    WIDTH - PENALTY_WIDTH,
    (HEIGHT - PENALTY_HEIGHT) // 2,
)
RIGHT_PENALTYAREA_CORNER_LEFT_DOWN = (
    WIDTH - PENALTY_WIDTH,
    (HEIGHT - PENALTY_HEIGHT) // 2 + PENALTY_HEIGHT,
)
LEFT_PENALTYAREA_CORNER_RIGHT_UP = (PENALTY_WIDTH, (HEIGHT - PENALTY_HEIGHT) // 2)
LEFT_PENALTYAREA_CORNER_RIGHT_DOWN = (
    PENALTY_WIDTH,
    (HEIGHT - PENALTY_HEIGHT) // 2 + PENALTY_HEIGHT,
)
LEFT_PENALTYAREA_CORNER_LEFT_UP = (0, (HEIGHT - PENALTY_HEIGHT) // 2)
LEFT_PENALTYAREA_CORNER_LEFT_DOWN = (0, (HEIGHT - PENALTY_HEIGHT) // 2 + PENALTY_HEIGHT)
RIGHT_GOALAREA_CORNER_RIGHT_UP = (WIDTH, (HEIGHT - GOALAREA_HEIGHT) // 2)
RIGHT_GOALAREA_CORNER_RIGHT_DOWN = (
    WIDTH,
    (HEIGHT - GOALAREA_HEIGHT) // 2 + GOALAREA_HEIGHT,
)
RIGHT_GOALAREA_CORNER_LEFT_UP = (
    WIDTH - GOALAREA_WIDTH,
    (HEIGHT - GOALAREA_HEIGHT) // 2,
)
RIGHT_GOALAREA_CORNER_LEFT_DOWN = (
    WIDTH - GOALAREA_WIDTH,
    (HEIGHT - GOALAREA_HEIGHT) // 2 + GOALAREA_HEIGHT,
)
LEFT_GOALAREA_CORNER_RIGHT_UP = (GOALAREA_WIDTH, (HEIGHT - GOALAREA_HEIGHT) // 2)
LEFT_GOALAREA_CORNER_RIGHT_DOWN = (
    GOALAREA_WIDTH,
    (HEIGHT - GOALAREA_HEIGHT) // 2 + GOALAREA_HEIGHT,
)
LEFT_GOALAREA_CORNER_LEFT_UP = (0, (HEIGHT - GOALAREA_HEIGHT) // 2)
LEFT_GOALAREA_CORNER_LEFT_DOWN = (0, (HEIGHT - GOALAREA_HEIGHT) // 2 + GOALAREA_HEIGHT)


LANDMARK_LIST = [
    GOALPOST_LEFT_UP,
    GOALPOST_LEFT_DOWN,
    GOALPOST_RIGHT_UP,
    GOALPOST_RIGHT_DOWN,
]

LANDMARK_PENALTYPOINT = [PENALTY_MARK_LEFT, PENALTY_MARK_RIGHT]

LANDMARK_XCROSS = [
    PENALTY_MARK_LEFT,
    PENALTY_MARK_RIGHT,
    KICKOFF_MARK,
    CENTORLINE_CIRCLE_INTERSEC_UP,
    CENTORLINE_CIRCLE_INTERSEC_DOWN,
]

LANDMARK_LCROSS = [
    RIGHT_CORNER_UP,
    RIGHT_CORNER_DOWN,
    LEFT_CORNER_UP,
    LEFT_CORNER_DOWN,
    RIGHT_PENALTYAREA_CORNER_LEFT_UP,
    RIGHT_PENALTYAREA_CORNER_LEFT_DOWN,
    RIGHT_GOALAREA_CORNER_LEFT_UP,
    RIGHT_GOALAREA_CORNER_LEFT_DOWN,
    LEFT_PENALTYAREA_CORNER_RIGHT_UP,
    LEFT_PENALTYAREA_CORNER_RIGHT_DOWN,
    LEFT_GOALAREA_CORNER_RIGHT_UP,
    LEFT_GOALAREA_CORNER_RIGHT_DOWN,
]

LANDMARK_TCROSS = [
    RIGHT_PENALTYAREA_CORNER_RIGHT_UP,
    RIGHT_PENALTYAREA_CORNER_RIGHT_DOWN,
    RIGHT_GOALAREA_CORNER_RIGHT_UP,
    RIGHT_GOALAREA_CORNER_RIGHT_DOWN,
    LEFT_PENALTYAREA_CORNER_LEFT_UP,
    LEFT_PENALTYAREA_CORNER_LEFT_DOWN,
    LEFT_GOALAREA_CORNER_LEFT_UP,
    LEFT_GOALAREA_CORNER_LEFT_DOWN,
    CENTORLINE_SIDELINE_INTERSEC_UP,
    CENTORLINE_SIDELINE_INTERSEC_DOWN,
]

NUM_OF_ROBOTS = 6  # ロボットの数（味方3、敵3）
ROBOTS_ID_LIST = [
    i + 1 for i in range(NUM_OF_ROBOTS)
]  # ロボットのIDリスト（1-indexed）


class ObjectLabel(enum.IntEnum):
    LABEL_BALL = 1
    LABEL_GOALPOST = 2
    LABEL_ROBOT = 3
    LABEL_OPPENENT = 4
    LABEL_TCROSS = 5
    LABEL_XCROSS = 6
    LABEL_LCROSS = 7
    LABEL_PENALTYPOINT = 8
    LABEL_UNKNOWN = 99


def convert_objectlabel_to_str(label: ObjectLabel) -> str:
    if label == ObjectLabel.LABEL_BALL:
        return "Ball"
    elif label == ObjectLabel.LABEL_GOALPOST:
        return "Goalpost"
    elif label == ObjectLabel.LABEL_ROBOT:
        return "Person"
    elif label == ObjectLabel.LABEL_OPPENENT:
        return "Opponent"
    elif label == ObjectLabel.LABEL_TCROSS:
        return "TCross"
    elif label == ObjectLabel.LABEL_XCROSS:
        return "XCross"
    elif label == ObjectLabel.LABEL_LCROSS:
        return "LCross"
    elif label == ObjectLabel.LABEL_PENALTYPOINT:
        return "PenaltyPoint"
    else:
        return "Unknown"


LABEL_LIST = [
    ObjectLabel.LABEL_BALL,
    ObjectLabel.LABEL_GOALPOST,
    ObjectLabel.LABEL_ROBOT,
    ObjectLabel.LABEL_OPPENENT,
    ObjectLabel.LABEL_UNKNOWN,
]

CONVERT_SCALE = 1.0 / 100.0  # 実機はm単位なのでそれに変換する係数


class GoalType(enum.Enum):
    LEFT = "ally"  # 味方ゴール
    RIGHT = "enemy"  # 敵ゴール
    NONE = "none"  # ゴールではない
